name: Setup
description: Setup the environment for the other jobs and steps

runs:
    using: composite
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
          with:
              node-version-file: package.json
              cache: 'npm'

        - name: Install
          run: npm install
          shell: bash

        - name: Compile
          run: npm run compile
          shell: bash
