// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import { IPoolManagerLogic } from "../interfaces/IPoolManagerLogic.sol";
import { IHasSupportedAsset } from "../interfaces/IHasSupportedAsset.sol";

/**
 * @title FundCalculationLibrary
 * @dev Stateless utility library extracted from PoolLogic to reduce bytecode size.
 */
library FundCalculationLibrary {

    /**
     * @dev Best-effort ERC20 balanceOf(asset, who). Returns (success, balance).
     *      Uses staticcall so non-ERC20 assets (e.g., NFTs) don't revert the whole withdraw.
     */
    function tryBalanceOf(
        address asset,
        address who
    ) internal view returns (bool success, uint256 bal) {
        (bool ok, bytes memory ret) =
            asset.staticcall(
                abi.encodeWithSignature("balanceOf(address)", who)
            );
        if (!ok || ret.length != 32) return (false, 0);
        return (true, abi.decode(ret, (uint256)));
    }

    /**
     * @dev Computes token price given fund value and token supply.
     */
    function tokenPrice(
        uint256 fundValue,
        uint256 tokenSupply
    ) internal pure returns (uint256 price) {
        if (tokenSupply == 0 || fundValue == 0) return 0;
        price = (fundValue * 1e18) / tokenSupply;
    }

    /**
     * @notice Get available manager fee of the pool internal call
     * @param _fundValue The total fund value of the pool
     * @param _tokenSupply The total token supply of the pool
     * @param _performanceFeeNumerator Performance fee numerator
     * @param _managerFeeNumerator Management fee numerator
     * @param _feeDenominator Fee denominator
     * @return performanceFee Performance fee generated by the pool (in pool tokens)
     * @return streamingFee Management fee generated by the pool (in pool tokens)
     */
    function availableManagerFee(
        uint256 _fundValue,
        uint256 _tokenSupply,
        uint256 _performanceFeeNumerator,
        uint256 _managerFeeNumerator,
        uint256 _feeDenominator,
        uint256 tokenPriceAtLastFeeMint,
        uint256 lastFeeMintTime
    ) internal view returns (uint256 performanceFee, uint256 streamingFee) {
        if (_tokenSupply == 0 || _fundValue == 0) return (0, 0);

        uint256 currentTokenPrice = (_fundValue * 1e18) / _tokenSupply;

        // Performance fee based on price increase since last fee mint
        if (currentTokenPrice > tokenPriceAtLastFeeMint) {
            uint256 feeUsdAmount = (
                (currentTokenPrice - tokenPriceAtLastFeeMint) *
                    _performanceFeeNumerator *
                    _tokenSupply
            ) / (_feeDenominator * 1e18);

            // Convert USD fee amount to pool token amount
            // performanceFee = feeUsdAmount / (fundValue - feeUsdAmount) * tokenSupply
            performanceFee =
                (feeUsdAmount * _tokenSupply) /
                (_fundValue - feeUsdAmount);
        }

        // Streaming (management) fee from lastFeeMintTime to now
        if (lastFeeMintTime != 0) {
            uint256 timeChange = block.timestamp - lastFeeMintTime;
            streamingFee =
                (_tokenSupply * timeChange * _managerFeeNumerator) /
                _feeDenominator /
                365 days;
        }
    }

    // ============================================================
    // =            FUSD → ASSET CONVERSION HELPERS                =
    // ============================================================

    /**
     * @dev Converts a FUSD amount to the corresponding asset amount using PoolManagerLogic prices.
     *
     * SAME LOGIC AS PoolLogic._fusdToAssetAmount
     */
    function fusdToAssetAmount(
        address poolManagerLogic,
        uint256 fusdAmount,
        address asset
    ) external view returns (uint256 assetAmount) {
        if (fusdAmount == 0) return 0;

        if (!IHasSupportedAsset(poolManagerLogic).isSupportedAsset(asset)) {
            return 0;
        }

        uint256 price = IPoolManagerLogic(poolManagerLogic).getAssetPrice(asset);
        if (price == 0) return 0;

        uint256 decimals = IPoolManagerLogic(poolManagerLogic).assetDecimal(asset);

        // FUSD is USD-18
        uint256 assetAmount18 = (fusdAmount * 1e18) / price;

        if (decimals == 18) {
            assetAmount = assetAmount18;
        } else if (decimals < 18) {
            assetAmount = assetAmount18 / (10 ** (18 - decimals));
        } else {
            assetAmount = assetAmount18 * (10 ** (decimals - 18));
        }
    }
}

    
