name: TESTS

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    tests:
        name: TESTS
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

            - name: Setup
              uses: ./.github/actions/setup

            - name: Branch parity check
              run: bash scripts/check-branch-parity.sh

            - name: Test
              run: npm run coverage # or npm run test
